### PR TITLE
Update _content/es from Lokalise

### PR DESCRIPTION
**Pull request by rousik**

### CODE REVIEW

**Comment by rousik** [comment]
@monicacecilia, feel free to check the preview build to make sure everything looks good.

**Comment by monicacecilia** [comment]
Hi @rousik, thanks for the heads up. I had a look and the preview site looks ok. All content is being displayed as it was intended in the last round on Lokalise. I figured out the switch for the svg magic and all images are now being displayed again. 
I see that the build is failing a check (up there ^^), but I, of course, leave that to the site experts. :bowtie: 
All good from my end! 
Thanks again! 🌺

**Comment by rousik** [comment]
Looks like build_and_deploy uses some fixed-naming-magic that is broken, @bcardiff fyi.

**Comment by bcardiff** [comment]
It seems more an issue of configuration of the secrets in the project.
But it's odd since those didn't change.

compare https://github.com/flattenthecurve/guide/runs/647412560?check_suite_focus=true#step:5:34
and https://github.com/flattenthecurve/guide/runs/675431429?check_suite_focus=true#step:5:49

Yet, the deployment of this PR is available at https://guide-preview-fqj3j3ait.now.sh/

**Comment by rousik** [comment]
@bcardiff I don't think this has to do with secrets because the preview is pushed to vercel, but script then fails to retrieve the deployment url.

I have opened #402 to track this problem. My prime suspect is that version upgrade of now cli causes this.

**Pull request merged**
