### PR TITLE
fixes #53 Update image, tweet in Spanish page

### LINKED ISSUE #53: Update image, update Tweet in Spanish translation
- [x] **Update/remove wrong tweet**: In the section "```Hay que abastecerse de comida y elementos esenciales – temprano, gradual, y responsablemente```": the wrong Tweet was embedded in the Spanish translation. What's currently there is a tweet from Florian Krammer; which was also correctly added (a second time) later in the text. Although it is not in the English page, if you want to embed a tweet in this section, it should be this one instead (from Emma Hodcroft; correctly linked from the text) --> https://twitter.com/firefoxx66/status/1233666678841597952 
- [x] **Update to translated image**: In the section "```No vayas a reuniones que no sean esenciales```": the image with the text in English should be replaced with the one in Spanish, which can be found at -->  [/images/es/Riesgo-producir-muerte.png](https://github.com/flattenthecurve/guide/blob/master/images/es/Riesgo-producir-muerte.png)

### PR DESCRIPTION
**Pull request by monicacecilia**
fixes #53 
- Update image 'risk of allowing death' to Spanish page
- Update embedded tweet

### CODE REVIEW

**Comment by bcardiff** [comment]
@monicacecilia, We've clarified [how to handle the translations flow](https://github.com/flattenthecurve/guide#update-english-text-to-lokalise). This edits should be go into lokalise so we can grab content from there.

If there are images needed a PR is the way to upload them for now.

**Comment by monicacecilia** [comment]
I hope this is useful. Not text changes: images and embedded links.

**Comment by bcardiff** [comment]
I think that image is already in the repo as Riesgo-producir-muerte

**Comment by monicacecilia** [comment]
> @monicacecilia, We've clarified [how to handle the translations flow]
> If there are images needed a PR is the way to upload them for now.

Yes, it is clear to me that text needs to be updated using Lokalise. I already signed up. 

- There are not text updates here, only updating one image (it was still the one in English). Updated the filename so there is no confusion (as you updated a filename before, I'm following suit). 
- I also updated a link. Someone had embedded the wrong link in a section. 

Please let me know if images and links to embedded tweets should also be done in Lokalise.

**Comment by monicacecilia** [comment]
> I think that image is already in the repo as Riesgo-producir-muerte

Yep. I figured it would be best to be as "clean" as possible with file names as well, to avoid possible misinterpretation. Please delete if you don't think it's helpful.

**Comment by bcardiff** [comment]
All files from _content folder that are not english are imported fully from lokalise. So even if the changes are images links they will be lost in the next lokalise import, unless these changes are updated there.

**Pull request merged**
