### PR TITLE
Add links to some mutual aid resources

### PR DESCRIPTION
**Pull request by spestana**
This is addressing #60 and could be greatly expanded upon if needed, or moved to a different section.

### CODE REVIEW

**Comment by jmcmurry** [comment]
@nicolevasilevsky I agree we need big disclaimers.

**Comment by mverzilli** [comment]
Maybe we should hold on this until we have a longer term solution for the resources page then

**Comment by steesdale** [comment]
The first of the links goes to a protected google drive folder.  I think we should remove or fix this.  
https://docs.google.com/document/d/1dpMzMzsA83jbVEXS8m7QKOtK4nj6gIUk1U1t6P4wShY/edit

Does anyone have a proper link for this?

**Comment by nditada** [comment]
There is now a Resources section for holding all these links, could you please submit them there? Link to submission form in this page: https://www.flattenthecurve.com/resources/

**Pull request closed without merging**
