### PR TITLE
Refactor import_languages.rb script and allow for optional pending-sci-review

### PR DESCRIPTION
**Pull request by rousik**
The core of this change is to allow inserting pending-sci-review notice to act_and_prepare articles. To allow for this, the structure of the language import script has been refactored so that this could be done relatively cleanly.

Here's the brief summary of the changes:
1. added --sci-review-notice flag which will trigger insertion of pending-sci-review notices for translations that are not marked as reviewed in Lokalise
2. Refactoring of the code that pulls translations from Lokalise. The code has been moved to a function which allows us to specify whether we want to retrieve translations or only reviewed keys. The code returns JSON instead of generating local files under `_translations/` and the method is called twice by default to find out which keys are not scientifically reviewed.
3. Files under `_translations/` are now generated from in-memory json. This generates *almost* the same content but results in some whitespace changes.
4. If SINGLE_LANG is specified, request to Lokalise will only fetch the translations for given language (minor optimization).

As far as the sci-review-pending notice goes, this will get inserted into the translated text after the last header line (or at the beginning of the file if no headers are found). This is somewhat strange but it seems to be the only way to get the notice in the right place. Unless we make some dramatic changes to the styling of these markdown files that would remove all headers this should work just fine.

### CODE REVIEW

**Comment by bcardiff** [comment]
I'm not 100% sure but it seems that this broke something in the CI. All the "Preview translations" workflows are failing now.
https://github.com/flattenthecurve/guide/actions?query=workflow%3A%22Preview+translations%22

Maybe is the user context https://github.com/flattenthecurve/guide/commit/76e2a7b4656e43203dea0a94e2d996c0842cf592#diff-0fff584a8af28d53dbf23320ade81ee0R12 ?

Failing since https://github.com/flattenthecurve/guide/runs/622727974?check_suite_focus=true
Last success https://github.com/flattenthecurve/guide/runs/621149872?check_suite_focus=true

**Comment by rousik** [comment]
Yep. I'm aware of that. I have mentioned this on Slack earlier today. It
seems to me that ruby caching has gone bad. I don't understand how that
works so I don't know if I can debug but I discovered that not using the
docker-compose.ci.yml overrides does fix the problem (but also breaks the
caching).

Do you have insights into why the caching logic may be failing? I did
change the imports for the script recently.

**Comment by bcardiff** [comment]
Since removing docker-compose.ci.yml solves the issue and the user on the docker run changed recently I would bet that the stored cache has wrong pemissions.

I would try changing _both occurences_ in https://github.com/flattenthecurve/guide/blob/master/.github/workflows/preview-translations.yml#L14-L16 of `${{ runner.os }}-gems-` to `${{ runner.os }}-gems-v2-` havoc the cache and see how it goes.

**Comment by rousik** [comment]
K, will do tomorrow.

**Comment by rousik** [comment]
It seems that the change of uid was not the right thing to do so I'm
reverting that in https://github.com/flattenthecurve/guide/pull/383 (awaiting
review)

**Comment by rousik** [comment]
Hey Brian, what is the best way to get in touch with you if I want to ask
some questions? I assume you're not on the flattenthecurve slack workspace.
Feel free to shoot me email at rousik gmail if you're willing.

**Comment by bcardiff** [comment]
HI @rousik a mention in github should be enough. 

My current allocations are not in this project. nditada and matiasgarciaisaia are coworkers and can reach me in our slack if needed. I noticed the errors since I set up the build started receiving some alerts in my inbox :-).

**Pull request merged**
