### PR TITLE
Properly escape colon within YAML

### PR DESCRIPTION
**Pull request by jaysonvirissimo**
Hopefully closes [this](https://github.com/flattenthecurve/guide/issues/299) issue

### CODE REVIEW

**Comment by mverzilli** [comment]
@rousik this might point to a possible enhancement to the import script, right?

**Comment by emersonthis** [comment]
@jaysonvirissimo Thanks for this! It almost works but there's one more stray colon in [another file](https://github.com/flattenthecurve/guide/blob/master/_resources/2020-04-03-coronavirus-the-science-explained.md). The second one appears to be a duplicate of the one you fixed, so it can maybe be deleted, but I don't know much about that section of content... Good work!

**Comment by jaysonvirissimo** [comment]
I fixed the other file, but we should open a new issue for the duplicate resources. 👍

**Comment by emersonthis** [comment]
No more errors! And faster, too

**Comment by rousik** [comment]
We also need to fix `_scripts/import_resources.py` otherwise it will overwrite these changes on the next resource PR. What we probably need is 1. flag to allow for skipping over resources that already exist, 2. escaping of strings in the YML portion of the document.

**Comment by emersonthis** [comment]
@rousik Good catch. I don't know anything about the py script. Is this difficult to do? Are you able to coordinate with @jaysonvirissimo to make this happen? For the escaping issue, could it be as easy as just `"` quoting `"` every title? My understanding is that's still valid YAML, even if it's unnecessary in most cases. Just an idea.

**Comment by rousik** [comment]
I got https://github.com/flattenthecurve/guide/pull/305 to address these underlying problems.

**Comment by rousik** [comment]
I fixed the script now. I did not realize this snippet was yaml so now I'm
using yaml.dump() to generate it and that takes care of the escaping
properly. Thanks for highlighting this issue!

**Comment by rousik** [comment]
I also got another PR https://github.com/flattenthecurve/guide/pull/306 which
regenerates all existing resources and correctly escapes everything. That
PR might be all we need instead of this localized fix.

**Comment by jaysonvirissimo** [comment]
I close this PR if/when [this](https://github.com/flattenthecurve/guide/pull/305) and [this](https://github.com/flattenthecurve/guide/pull/306) get merged. 👍

**Comment by jaysonvirissimo** [comment]
Closing, since [this](https://github.com/flattenthecurve/guide/commit/9e4825b80b32b4b8fbfc4257119b361a93f36245) apparently fixed the root cause.

**Pull request closed without merging**
