### PR TITLE
Fixes to the resource page

### PR DESCRIPTION
**Pull request by rousik**
This is a second part of https://github.com/flattenthecurve/guide/pull/305 (should be only integrated once the other PR is in).

This PR:
1. switches to lowercase url attribute for resources (to eliminate need for special treatments)
2. properly escapes all resource attributes & removes some ad-hoc empty lines in the resource files
3. Converts United States to USA in one of the resource files. [1]

[1] it might be worth creating automatic rule converting the country name to the canonical form when new resource submission is received.

### CODE REVIEW

**Comment by rousik** [comment]
I have reverted the changes to `_scripts/import_resources.py` so that this can be merged into master independently of the other PR.

**Comment by rousik** [comment]
@jaysonvirissimo, @emersonthis and/or @mverzilli - please approve.

**Comment by emersonthis** [comment]
I added the "on hold" label to signal that this shouldn't be merged until #305 is merged.

**Comment by rousik** [comment]
I made this actually independent PR that can be merged as-is w/o having to
wait for the other one

**Pull request merged**
