### PR TITLE
Czech translation

### PR DESCRIPTION
**Pull request by nditada**

### CODE REVIEW

**Comment by mverzilli** [comment]
What's blocking this?

**Comment by nditada** [comment]
@Jan Rous is fixing a few things in #translation-czech still

**Comment by rousik** [comment]
Sorry for the delays. My workflows are still not fine-tuned and I occasionally miss the notification to know that I can keep on working on this. I will try to straighten out the kinks tomorrow morning. My take would be that it might be worth releasing this early and work out the kinks in the subsequent update but I don't know if we have some best practices around that. I suppose that the guiding principle should be "better okay now than perfect later", just like with the public response.

**Comment by rousik** [comment]
I have fixed the most obvious errors. If you could refresh the preview I can take another look tomorrow morning (Mountain Time) and we should be good to launch this.

**Comment by rousik** [comment]
One thing that was apparent during the translation is that the original page is fairly US-centric in some of its sections/analyses and this may not be of relevance to people in different countries. E.g. the section about why the epidemic will be bad in US and information about the recent bills are nice to know, but they're really not relevant to people dealing with the epidemic in the context of European countries. I wonder what would be the right approach here. I don't know if we could omit some paragraphs or even have way to include locally relevant content instead.

**Comment by matiasgarciaisaia** [comment]
Here's the preview: https://guide-preview-fi63hgc6q.now.sh/cs/

**Comment by matiasgarciaisaia** [comment]
This is the latest preview: https://guide-preview-hfz1krype.now.sh

It does look good to me - but I don't understand a single word of Czech.

**Comment by rousik** [comment]
I speak Czech and this looks good to me! We can launch now and fine-tune minor problems/details in subsequent releases.

**Comment by nditada** [comment]
@rousik regarding US-centrism: by all means, please adapt any section for country/cultural relevance, you don't need to translate US related portions of the text word by word. We should have made this much clearer in the beginning, you are not the first one to ask.

**Comment by rousik** [comment]
Replacing us-centric content with locally appropriate things will likely have to be tackled in subsequent reviews by someone else. Although I do speak Czech I live in US so I'm more familiar with US-centric aspects of this situation anyhow.

**Comment by nditada** [comment]
We have the approval to go live with this if we add a disclaimer at the top with something like "Translation not yet scientifically verified"  (In Czech, of course)

**Comment by rousik** [comment]
In Czech, that message should read: Český překlad zatím nebyl ověřen vědeckou komunitou.
Literally: The translation has not been verified by the scientific community.

I'm not sure where this lang-specific message should be injected & do not own this PR, but having this message should, I  hope, help.

**Comment by mverzilli** [comment]
I think it's enough with 2 places:

1. At the top of the home page
1. At the top of Act & Prepare

**Comment by Leco2572** [comment]
Hi. I was told to have a look on the czech version of the flattenthecurve - probably because I treat ICU patients with Covid 19 in a university teaching hospital. As for me it works (sounds not very elegant but it works- like my English).

**Pull request merged**
