### PR TITLE
Switch to theme "minimal-mistakes"

### PR DESCRIPTION
**Pull request by jaeddy**
This is a fairly hefty PR that switches the Jekyll theme from "minima" to "minimal-mistakes" (see the [docs site](https://mmistakes.github.io/minimal-mistakes/) for more info). Besides looking nicer (in my opinion) the theme supports a lot of other UX features and service integrations out of the box — so hopefully less customization moving forward.

Here's a snapshot of the new layout:
image

The TOC now "floats" on the left and subsections will expand when they're in view:
image

Two drawbacks of the current setup:

1. minimal-mistakes is technically installable via a gemfile, but there were still a number of things I needed to customize — so a lot of the files are copied from a fork of their repo for now;
2. I wasn't sure what some of the code in `head.html` and `header.html` were doing; I renamed the latter with the suffix `_old` and kept the latter, so hopefully we don't lose anything important — I can try to help merge, if anyone can point me in the right direction.

### CODE REVIEW

**Comment by bcardiff** [comment]
* In 8d2b5247fd773e0b88dd7e32c5d54c1bd96a759e I fixed some issues that were preventing the docker environment to start after these changes.
* The sidebar does not scroll, only the main content, so the experience is not great IMO
  * When the do/don't section are expanded this issue is more important. [sample of scrolling over the sidebar](https://recordit.co/mJChDj0NkH)
  * Keep in mind that due to #40 we might revert f8c5d5639091d59154917b7f52f157204017cec5 showing longer titles.
* There is a Recent Posts item and the end of the sidebar that should be removed
* `og:image` added by ca7707a545c39845aba0c010b89dea29aa200646 is gone
* favicon added by fe509c507abdc9b50a4f4d6ccfaab356032d923b is gone, the root favicon.ico is still used, but the reference to the png are gone.
* changes of font by b391d01287976ceabfa044316bfd497f18a83634 / #63 are gone
* js/main.js add by 8b50de3a1432bdaf41b35f0dc8d51d60dcbb9ea3 is no longer needed

Preview is available on https://guide-preview-burkhsi5v.now.sh/

**Comment by jaeddy** [comment]
Thanks, @bcardiff! I'll take a look at the remaining issues (the Recent Posts item was especially confusing when I encountered it earlier).

Regarding the sidebar, this is configurable with the 'toc_sticky' option. However, I intentionally made the ToC fixed in place because the page is so long - once you scroll past the ToC, there's no way to navigate between sections or back to the top. I'm open to alternative approaches (e.g., inserting 'back to top' links after each section, breaking the content over multiple pages). I got the impression that either of those changes would require potentially more complicated refactoring (given the current way in which md files are combined into a single page), but we could certainly rethink the organization.

I'm definitely not a web developer, so I defer to the judgment of others on these decisions.

**Comment by jaeddy** [comment]
OK - I think I addressed most of the issues listed above (with the exception of the general ToC side-nav behavior). I think the reversion to longer titles is ill advised (some of these "titles" are now effectively short paragraphs), but I'll raise that concern in a separate issue. For now, I think things should mostly work — but let me know if there are any other changes to make.

**Comment by bcardiff** [comment]
In the technical aspects I have one thing to mention that I fixed in 730e50b973279b221a29e4bde8f98d497ca44f6b, the short titles we been displayed in the main content again.

You addressed all the other techy things I mentioned.

But I am still concerned on the UX. 
* Since the sidebar does not scroll, if the window height is small the user has no way to reach some of the headlines.
* Before going to mobile the layout is broken a little bit
* In mobile there is no way to expand the second level headlines in the toc so we lost that navigation

Sample interaction: https://recordit.co/Xjful4VWv2
Preview url (with the fix for the short titles): https://guide-preview-nbgr96vhz.now.sh/

**Comment by jaeddy** [comment]
Thanks again, @bcardiff. I didn't realize how to check mobile behavior until this morning, so I can make sure to keep an eye on that in future commits.

I also see what you mean now about the sidebar UX issues. I think the problem(s) the sticky, collapsing/expanding ToC aims to solve will go away with some of the site restructuring that's currently being discussed by @nditada and others (i.e., the page and the ToC hopefully won't need to be so ***long***).

In light of this and some of the other QA issues with this large PR, I'm going to close for now and wait until we have a concrete plan for the design. We can re-open or cherry-pick as needed.

**Pull request closed without merging**
