### PR TITLE
Reorganized What to Do

### LINKED ISSUE #294: Reorganize DOs and DON'Ts content
It's been widely agreed that the current structure no longer makes sense. The plan is to divide the content into smaller thematic "chunks". The exact strategy is still being discussed [on Slack](https://flatten-the-curve.slack.com/archives/CV619KQUB/p1585887711004300).

This issue will get updated as that work takes shape...

### PR DESCRIPTION
**Pull request by emersonthis**
Eventually closes #294 

**Done (English only)**
* Re-organized the posts into new categories
* _Quickly_ updated a few of the posts that contained obviously out-of-date content
* Tweaked a few titles that had confusing wording
* Removed css class dependencies from posts (now they're only markdown)
* Added support for body classes (for cleaner better CSS)
* Cleaned up and also removed unused CSS styles

**Not done (yet)**
* Update other language posts
* ~Update other language page~

**_"But you removed the red and green colors from the titles! Booooo! Why???"_**  😫
There are a few reasons why:
* We no longer have a clear "DO" and "DON'T" distinction. For example: is "Avoid crowds" a DO or a DON'T? We need a design that doesn't force this distinction. Also there's added complexity from the fact that we're translating into many other languages whose grammar may or may not match the way English handles DOs and DONTs...
* The big red/green stripes were adding a lot of visual weight that were overpowering the _parent_ headings, which are more important now that we have more of them.
* The implementation of the DO / DON'T colors required a bunch of inline css classes, and this has hindered the translation workflow. (We can figure out a better way to do it later, but let's get the info out there first!)

Screen Shot 2020-04-08 at 9 41 11 PM

### CODE REVIEW

**Comment by emersonthis** [comment]
@mverzilli @nditada If you give me a thumbs up on this, I'll loop back and update the other language files as much as I can before removing the WIP label.

**Comment by jmcmurry** [comment]
From a content perspective, this all looks great. I can't speak to the technical aspect as changing 64 docs at once is hard to track the impact of. Is there a staging area we can view these in?

**Comment by nditada** [comment]
@emersonthis this looks good to me from a structure standpoint and @jmcmurry gave her ok in terms of content, so we are good to go. Did you mean this PR as a WIP or shall we merge and then adapt the other languages?

**Comment by emersonthis** [comment]
@nditada I'd vote for merging as soon as possible, but let me know if there's specific things I can do to make the translators' job easier. If not, let's merge.

**Comment by emersonthis** [comment]
@jmcmurry I added the flu buddy back in.

I think this might be ready to merge.

**Comment by emersonthis** [comment]
> Is there a staging area

Yes. There’s a link above to a deployed preview of this PR

**Comment by jaysonvirissimo** [comment]
Not sure if we have an actual QA process, but things LGTM on the https://guide-preview-bpj9miuzy.now.sh deploy. 👍

**Comment by emersonthis** [comment]
I agree. I think this can get merged but I want @nditada to endorse because I don’t understand the implications for translations well enough to feel confident merging this myself. If someone can speak on this that would work too.

**Comment by rousik** [comment]
@emersonthis I have tried to integrate your changes and rerun import_languages.rb on DE and CS languages. As you can see here, this doesn't quite work well:
https://guide-preview-gqdakh65n.now.sh/de/act-and-prepare/

I have not yet looked into why is it happening but it seems not safe as-is.

**Comment by rousik** [comment]
Your changes combined with the language refresh for de,cs languages can be found in the branch `preview/issue-294-translations`

**Comment by rousik** [comment]
The problem seems to be due to large number of untranslated keys (10 per language):

```
./_sections/act_and_prepare/cs/05-reduce-stress/00-tips-to-reduce-stress.md
./_sections/act_and_prepare/cs/04-support-community/15-donate.md
./_sections/act_and_prepare/cs/04-support-community/00-how-to-support-your-community.md
./_sections/act_and_prepare/cs/02-household-practices/05-shop-carefully.md
./_sections/act_and_prepare/cs/02-household-practices/06-pandemic-pal.md
./_sections/act_and_prepare/cs/02-household-practices/00-household-practices.md
./_sections/act_and_prepare/cs/01-not-infected/02-avoid-crows.md
./_sections/act_and_prepare/cs/01-not-infected/00-how-to-not-get-infected.md
./_sections/act_and_prepare/cs/01-not-infected/01-stay-home.md
./_sections/act_and_prepare/cs/03-if-sick/00-what-to-do-if-you-get-sick.md
```

My understanding is that basenames of markdown files are used to construct Lokalise keys (e.g. stay-home). If you move file into another directory or change its numerical prefix, that should not be a problem, but changing filename itself will dissociate it from the existing translations.

I can see that this is happening for some files listed above, e.g.:

```
shop-when-at-risk -> shop-carefully
stay-connected -> avoid-crows
```

The simplest interim solution to this problem would be to retain original naming wherever possible. Maybe there is a way to elegantly update Lokalise keys but I don't know about it yet.

The second problem is due to new content (h2 files for each section). I think for this we will simply need to kick off Lokalise task once your change is merged into head (I think that Lokalise is pulling keys out of master branch continuously).

**Comment by emersonthis** [comment]
@rousik i mostly understand everything you wrote. What needs to happen next in your opinion? The challenge for me right now is that I don’t know how much to “weigh” the issues for translations against the improvements to the English version. I don’t want to cause translation problems but it’s not clear whether some translations are going to catch up no matter what we do... and in the mean time the English version of this page is not very accessible. I don’t know how to make his call. @nditada help ;-)

**Comment by emersonthis** [comment]
Another factor to consider is that some of the translations that will “break” are for older versions of this content that need to be updated anyway. This PR was supposed to be a structural change before editing a bunch of these items for content improvements.

**Comment by rousik** [comment]
I think your reasoning is sound. Deploying this and then kicking off translations seems like a good order of operations. The translated pages should remain unaffected until after we pull the new strings from Lokalise so we should be safe until then.

If I'm reading [this Lokalise documentation](https://docs.lokalise.com/en/articles/1400528-key-referencing) right, there may be a way to link/group the duplicate keys which might allow us to associate these new strings with existing translations and that might make reduce the ops load on the translators.

**Comment by emersonthis** [comment]
Ok. I saw a 👍 from @nditada earlier and it sounds like you're on board. So I'm going to merge this. It'll take me a few minutes fix the merge conflicts (again) so if anyone has strong objections this is "last call" as they say...

**Comment by emersonthis** [comment]
I spoke too soon... I need at least one reviewer to approve before I can pull the trigger on merging this.

**Comment by rousik** [comment]
I will take a look at this tomorrow morning (Mountain Time) and once you
merge this I will try to fix up our translation strings in Lokalise.

**Comment by emersonthis** [comment]
@rousik thanks! This is a busy week for me, but let me know if I can help with the translation strings

**Comment by rousik** [comment]
Turns out that the changes to the content along with the change of
filenames makes duplicate finder not work. I will look into whether it's
possible to link those things or pre-populate new translations at least.

**Pull request merged**
