### PR TITLE
Add list of countries liking and mandating "masks for all" when in publc

### PR DESCRIPTION
**Pull request by paul-hammant**
Countries are beginning to implement masks or all when mixing in public policies now. Flattenthecurve should note that and track in.

### CODE REVIEW

**Comment by jaysonvirissimo** [comment]
Also, Austria is about to [make masks mandatory in supermarkets](https://orf.at/stories/3159909/).

**Comment by nicolevasilevsky** [comment]
@jaysonvirissimo is Austria mandating people wear masks now?

**Comment by jaysonvirissimo** [comment]
@nicolevasilevsky they become mandatory next week, but [supermarkets are already handing them out](https://www.reuters.com/article/us-health-coronavirus-austria-masks/austrian-supermarkets-hand-out-face-masks-before-they-become-compulsory-idUSKBN21J5Y9).

**Comment by nicolevasilevsky** [comment]
thanks @jaysonvirissimo. I'll update this PR

**Comment by nicolevasilevsky** [comment]
we need one more reviewer to sign off, then this can be merged

**Pull request merged**
