### PR TITLE
New Homepage

### LINKED ISSUE #213: Homepage redesign
Let's use this issue to centralize all discussions and links to relevant content to put in the next version of the Homepage. @jackiedelc, @emersonthis, @weltyj  and myself will lead this effort. 

Content is currently based in the following doc/s:

-https://docs.google.com/document/d/1m4HP1jIShnNqvxD5V7Q9MYbhU7pqSW1JAK89Q6WQ5zU/edit

Things we need to account for (feel free to suggest others):

- [ ] Where the current homepage content should go.
- [ ] GX design to better convey the new message.
- [ ] How this impacts versions of the site in other languages. 

Let's ship this! 💪

### PR DESCRIPTION
**Pull request by emersonthis**
(Mostly) closes #213 

## Done
* Global style updates
* New homepage content
* Lots of CSS organization
* Locally hosted web fonts
* Multi-col utility class(es)
* Fixed some of the repeated H1s

## TODO
* ~Properly organize the content that was on the homepage (and is now on the COVID-19 page) so that translations work. Help: @nditada cc @mverzilli~

Screen Shot 2020-03-26 at 9 43 15 PM

## Follow-up issues
* Tighten up the footer design
* Fix the remaining pages with multiple H1 tags
* Move ~"contribute"~ "Contact" out of the primary nav (into footer)
* Add Ivan's jazzy new logo(?)
* Convert language links to dropdown(?)
* Rename /act_and_prepare permalink to match new page title (what-do-do)? ...and figure out how to redirect the old path. I created [this branch](https://github.com/flattenthecurve/guide/tree/redirect-plugin) which adds [this redirect plugin](https://github.com/jekyll/jekyll-redirect-from) that seems to work, but I ran out of time before I could figure out how to get it to play nice with the translation plugin.

### CODE REVIEW

**Comment by mverzilli** [comment]
Looks great overall! Just a couple of comments below, mostly around follow up issues:

> Add Ivan's jazzy new logo

Let's park this for another time. Two reasons:

1. I'm a bit concerned about impacting readability. 
1. Changing the logo is something most of the org has to be onboard with. I don't see a need to make that change at the same time as this homepage overhaul. Let's leave it out so we reduce the list of issues we need to resolve before releasing.


> Move "contribute" out of the primary nav (into footer)

Can we leave it in both places for now? Or there was a broad discussion on removing Contribute from the navigation header and I missed it?


> Rename /act_and_prepare permalink to match new page title (what-do-do)?

Ideally we should keep both, what-to-do for consistency and act_and_prepare links into it around the internet can still reach the page. Someone should check Jekyll to see how it can get done. Nice catch raising up this issue!

**Comment by weltyj** [comment]
@mverzilli @matiasgarciaisaia I have a copy of this branch locally and am working at fixing that conflict, and getting the tree structure back into the canonical   _sections/<....>/<lang>/, which is easy.  Should Icreate the subdirectories for all the other languages other than "en", or will they autogenerate with the whole translation process?

**Comment by weltyj** [comment]
@emersonthis @mverzilli    I looked at all the languages on my little cellphone -- all menus function in all languages.   Looks good to go from that standpoint

One bad image link I found.   Simple edit in _sections/COVID-19/en/06-keep-the-main-thing-the-main-thing.md
This link needs a leeding "/" (like so)

**Comment by emersonthis** [comment]
Sorry for the confusion about “contribute”... I meant “contact” which I think was discussed with Nico last week.

About the list of future issues... I included those mostly to indicate things I knowingly did not include in this PR (and don’t plan to). So of course we can hold off on any of them, like the logo, etc

**Comment by weltyj** [comment]
Oops, I found two more image links needing a leading slash in 
_sections/COVID-19/en/05-this-is-not-normal-flu.md

**Comment by weltyj** [comment]
I confess I'm at the limit of my git understanding.   There maybe a better way to do this, but I pulled the issue-213 branch and made the small edits to correct the image links -- and create a "en" directory in _sections/04-about/ .   I made a new branch with my edits.  I DID NOT create a PR for this in order to avoid confusion.  @emersonthis @mverzilli here is the branch:

https://github.com/flattenthecurve/guide/tree/jw-edits-issue-213

**Comment by weltyj** [comment]
Ideally we should keep both, what-to-do for consistency and act_and_prepare links into it around the internet can still reach the page. Someone should check Jekyll to see how it can get done. Nice catch raising up this issue!

^^^
I'll check into that.

**Comment by emersonthis** [comment]
I just merged @weltyj 's changes into this branch. That seems to have resolved the broken images and updated the other language versions touched by this. Anything left to solve before this can get merged?

**Comment by weltyj** [comment]
@mverzilli @bcardiff @emersonthis I would add a review approval, but it doesn't seem to meet the intention of the approval process since my edits are now part of the branch.  If you think it's ok for me to approve I will.

**Comment by emersonthis** [comment]
@mverzilli @nditada does this still need the “do not merge” label? I think everything mentioned above has been addressed. Let me know if there’s anything left for me to do on this.

**Comment by mverzilli** [comment]
Given how critical this change is, I've asked the other team leaders to confirm they're ok with the change as seen in the preview. Once they 👍 and you fix this link I'll merge. Amazing work @emersonthis 🙇

**Comment by weltyj** [comment]
https://github.com/flattenthecurve/guide/tree/issue-213-fix-dont-link
@emersonthis @mverzilli 

Early riser here :-)   That fixes the broken link which was pointing to #dont, needed to be #do-not in _sections/home/01-site-header.md

**Comment by emersonthis** [comment]
@mverzilli The link is fixed

**Comment by mverzilli** [comment]
Awesome! The only remaining bit to solve is what to do with the "STAY INFORMED" section. I'm raising that issue and will get to you as soon as I have further direction from core team. Sorry I didn't realize about that gap before :/

**Comment by emersonthis** [comment]
@mverzilli can you say a bit more about “the problem” that needs to be solved? I wasn’t aware there is an issue. Maybe we can propose solutions?

**Pull request merged**
