### PR TITLE
Reintroduce improved vitamin D recommendation

### PR DESCRIPTION
**Pull request by jaysonvirissimo**
A similar section was introduced [here](https://github.com/flattenthecurve/guide/pull/262), but then later removed.
[This](https://github.com/flattenthecurve/guide/issues/294#issuecomment-612298305) comment indicates the removal was intentional, but doesn't itself provide a rationale.
This set of changes (1) brings back the old section, (2) reorganizes it, and (3) supplies additional warrant for the recommendation in the form of a recently released RCT pertaining to COVID-19 specifically (rather than the mere analogical reasoning from respiratory diseases in general to the coronavirus in particular in the original version).

### CODE REVIEW

**Comment by jaysonvirissimo** [comment]
I expect @emersonthis and @jmcmurry to have the most context about whether this section should be included/not.

**Comment by emersonthis** [comment]
At the time when we removed it, it wasn’t clear that it met the criteria for advice to be included in the site. We were trying to focus on COViD-specific recommendations. Sounds like maybe it’s more relevant than we originally thought. There’s a doc in the linked issue that talks more about that decision process.

**Comment by jaysonvirissimo** [comment]
I see. In that case, I think it _should_ be re-included, since it now meets all four criteria mentioned in the linked issue.

**Comment by jaysonvirissimo** [comment]
@nditada, @rousik: CI's attempt to deploy a staging build via vercel is failing for lack of creds (`Error! No existing credentials found.`). Is that something you can re-run for me?

**Comment by jmcmurry** [comment]
I didn't realize that this didn't make it in and agree it should be there. I can force a merge

**Pull request merged**
